export const AllActions = {
  US_TICKERS_LOADED: 'US_TICKERS_LOADED',
  PRICE_TYPE_UPDATED: 'PRICE_TYPE_UPDATED',
  DATE_FROM_TO_UPDATED: 'DATE_FROM_TO_UPDATED',
  REMOVE_SELECTED_TICKER: 'REMOVE_SELECTED_TICKER',
  ADD_SELECTED_TICKER: 'ADD_SELECTED_TICKER',
  CANDLE_DATA_LOADED: 'CANDLE_DATA_LOADED',
} as const;
